### ISSUE TITLE
TesterHome 特有功能

### ISSUE THREAD

**Issue by lihuazhang** [testerhome/homeland#1]
- [x] TesterHome 独有样式
- [x] TesterHome 版权申明
- [x] 首页添加最新帖子列表
- [x] 匿名板块
- [x] 公开课和臭虫广播站节点
- [x] 微信打赏和打赏样式
- [x] 邮件配置
- [x] 酷站的favicon
- [x] 新帖排行榜只展示有回复和有赞的新帖[自己的赞不算]
- [x] greet 接口
- [x] 广告，推送到客户端的广告

**Comment by chenhengjie123** [comment]
想到了几个补充的点：

1. 招聘和 rubychina 要确认是不是同样的板块 id 。
2. wiki 改版应该也要加吧
3. 之前那个用户名重复的问题 rubychina 有没有解决，没有的话这个修复应该也要 merge 
4. 个人主页的类 github 活跃记录
5. 个人主页的个人标签

**Comment by lihuazhang** [comment]
@chenhengjie123 

招聘和 rubychina 要确认是不是同样的板块 id 。
wiki 改版应该也要加吧
之前那个用户名重复的问题 rubychina 有没有解决，没有的话这个修复应该也要 merge
个人主页的类 github 活跃记录

这几个都好了。
