### ISSUE TITLE
个人技能信息

### ISSUE THREAD

**Issue by DoctorQ** [testerhome/homeland#10]
# testerhome特有功能

## 线下
![4870617c-c13a-4d14-bf09-362da4ee7090](https://cloud.githubusercontent.com/assets/4489853/19968763/e426eede-a210-11e6-9638-6403c631c968.png)

正确显示如下

## 线上

![644b4950-8488-4005-89d5-fd42b45a965f](https://cloud.githubusercontent.com/assets/4489853/19968845/398b9280-a211-11e6-988b-ce46c06366f7.png)

**Comment by lihuazhang** [comment]
之前的实现不好，而且pg数据库的array支持有问题。暂时不做了。
