### ISSUE TITLE
首页，鼠标移动到话题上面，弹出简述的时候点进话题，然后返回，该简述不会消失

### ISSUE THREAD

**Issue by yu874721995** [testerhome/homeland#101]
![image](https://user-images.githubusercontent.com/33749158/105439671-3d6cdf00-5ca0-11eb-9a19-d15c9ecf5fa2.png)

**Comment by chenhengjie123** [comment]
和 https://github.com/testerhome/homeland/issues/94 重复了，这个先关闭
