### ISSUE TITLE
页面显示文章列表共60页，点击到>=3页时报错说“暂时没有文章或页数已超过最后一页”

### ISSUE THREAD

**Issue by mangoZHAN996** [testerhome/homeland#102]
复现地址：https://testerhome.com/columns/YunJiaSheQu?page=2
点击底部页码跳转到>=3页的地方
![image](https://user-images.githubusercontent.com/58100830/105468808-59897400-5cd2-11eb-882c-54ef87dad6cc.png)
实际结果：显示有60页，跳转到第3页提示无内容
![image](https://user-images.githubusercontent.com/58100830/105468847-6312dc00-5cd2-11eb-90cb-6fad9607291c.png)

**Comment by chenhengjie123** [comment]
内容确实只有2页，所以第三页开始都是提示已经超过最后一页。

底部写死60页，主要是出于让内容看起来比较丰富的考虑，是个有点取巧的设计。

**Comment by chenhengjie123** [comment]
考虑到专栏文章大多数页码不多，这个设计容易引起误会，后续会修复。相关修复事项在 https://github.com/testerhome/homeland/issues/90 里跟踪
