### ISSUE TITLE
开源项目榜单二期

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/homeland#103]
先记录下已知需求：

- [x] 非社区用户默认不显示，点击【显示全部】后再展示。（达峰、李隆）
- [x] 适配手机显示界面（李隆）
- [ ] 增加社区用户贡献情况榜单，展示社区用户在 github 上的贡献表现（代码提交数、follower 人数等），便于挖潜（达峰）
- [ ] 每个用户除了展示贡献指数，也展示他参与了其中哪些项目（恒捷）
- [ ] 增加不同项目的榜单，支持按项目来看榜单（恒捷）
- [ ] 优化代码，把目前用 dict 存储改为用 model ，降低由于底层修改 dict 结构导致上层得对应适配的成本、上层容错代码成本，提高编码效率。（恒捷）

**Comment by xudafeng** [comment]
个人namespace下有项目的同学，最好也能挖掘出来，鼓励加入ttf计划

**Comment by chenhengjie123** [comment]
前两项已完成：
https://github.com/testerhome/homeland/pull/104

**Comment by chenhengjie123** [comment]
确认第二期需完成需求：

- 增加社区用户贡献情况榜单，展示社区用户在 github 上的贡献表现（代码提交数、follower 人数等），便于挖潜（达峰）
-  每个用户除了展示贡献指数，也展示他参与了其中哪些项目（恒捷）
-  增加不同项目的榜单，支持按项目来看榜单（恒捷）
-  优化代码，把目前用 dict 存储改为用 model ，降低由于底层修改 dict 结构导致上层得对应适配的成本、上层容错代码成本，提高编码效率。（恒捷）

初步梳理下整合后的需求：

1、添加社区用户github贡献情况榜单。
1.1 榜单中的用户，仅包括有绑定 github 账户的用户。
1.2 每个用户的贡献指数=follower人数（表示影响力）*50%+名下项目 star 数（表示项目影响力）*30%+近一周activity 数（表示活跃程度）*20%
1.3 这个榜单以 tab 的形式，增加到 TTF贡献者榜单 中，并把标题栏中的 “TTF贡献者榜单” 改名为 “社区开源贡献者榜单”
1.4 榜单需增加分页功能（社区用户太多，不分页看起来会很累）

2、所有榜单，增加一列 参与项目 ，可把所有参与过的项目列出来，并把点击 url 改为查看此用户在该项目中的 commit 记录

3、在 TTF 榜单中，添加不同项目的榜单，项目为 macaca、httprunner、atx 三个。除榜单内所有数据均只会统计此项目外，其它和现有 TTF 总榜保持一致

4、技术优化，到技术方案时再沟通。

**Comment by xudafeng** [comment]
- [ ] repo 支持动态添加
- [ ] 优化展示上的体验，现在比较粗糙

**Comment by chenhengjie123** [comment]
> repo 支持动态添加

这个目前是有的，只是放在了后台，只有管理员可见。

> 优化展示上的体验，现在比较粗糙

有没有更具体的想法？展示这个我建议是找个比较不错的直接抄，这块不是我们擅长的部分。

> 周榜的鼓励机制是什么？

周榜指的是“社区用户github贡献情况榜单”？如果是，个人理解这个更多是辅助我们挖潜以及一些 github 贡献比较多的同学能有个地方曝光。榜单本身暂时没计划有其它鼓励机制。

**Comment by chenhengjie123** [comment]
榜单样式示例：
![image](https://user-images.githubusercontent.com/2800797/66049902-d5503200-e55e-11e9-95ca-3b2c2ba684d4.png)
![image](https://user-images.githubusercontent.com/2800797/66049910-d84b2280-e55e-11e9-9267-2f187985fb7c.png)

3个榜单

* 榜单1：就是现在的榜单，需要调整下体验， 将说明放到上面，功能区 增加一个checkbox框，和一个数量显示区，可以显示包括非社区用户后的总量
* 榜单2：贡献月榜，在当月贡献的榜单(周榜可能数据会非常少，前期按照月维度比较合适)，其实就是第一个榜单数据的的当月抽取。
贡献月榜 上要加上 鼓励的机制，比如赠书，增票(开源作者不在福利范围内)
* 榜单3：潜力总榜，所有有关联github用户的当年follow+commit数量统计
value = follow 数 + commit 数 / 2 比较合适，加入commit 数是为了让更活跃的用户出现

总体要求：
1、 榜单1 2 3 按照顺序出现在页面上，页面展开显示就好，不需要现在的左右布局
2、 每个账号既可以跳转到testerhome个人页(新开) github 个人页(新开)
3、左侧的序号始终是顺序排列下来

**Comment by chenhengjie123** [comment]
概要技术方案：

1、view 层，参照 ![](https://user-images.githubusercontent.com/2800797/66049902-d5503200-e55e-11e9-95ca-3b2c2ba684d4.png) 并行展示三个榜单，每个榜单带有说明区、功能区、榜单区。当屏幕空间缩小时，对应把并行榜单数量减少
2、controller 层，在现有榜单返回值基础上，增加另外两个榜单所需的数据。
3、model 层，现有 json 改为使用 model ，但不通过数据库持久化存储，而是序列化后存到 redis 中，便于定时任务更新数据。
4、定时任务层，保持不变。

详细技术方案：

* view 层

- [ ] 现有 `_opensource_contributor.html.erb` 支持通过传入不同的参数，展示不同的榜单
- [ ] 每个榜单页，都具备说明区（这个榜单的简要说明以及贡献指数计算公式）、功能区（是否显示非社区用户按钮）、榜单区（一行一个用户的形式展示榜单），并支持分页。说明区、功能区高度要一致。
- [ ] 现有 `index.html.erb` 榜单首页，并排展示3个榜单

* controller 层

- [ ] 现有 `index` 方法不变，但要把返回值从 json 改为 model 对象，里面包含三个榜单需要的数据，并支持分页（具体分页怎么做，待探究）。

* model 层

- [ ] 数据格式从 json 改为采用 model 格式。单条记录的数据库格式为：

```
github_user github用户名
is_testerhome_user 是否社区用户
contributed_repos 贡献过的 github 仓库 url ，多个时逗号分隔
ttf_contribution TTF榜单贡献指数
monthly_contribution 月度榜单贡献指数
discovery_contribution 潜力榜单贡献指数
```

- [ ] 添加 `_get_ttf_contributors` 方法，返回 TTF 贡献者榜单信息（按贡献指数从大到小排序，只显示前100名）
- [ ] 添加 `_get_monthly_conributors` 方法，返回贡献月榜榜单信息（按贡献指数从大到小排序，只显示前100名）
- [ ] 添加 `_get_discovery_contributor` 方法，返回潜力总榜信息（按贡献指数从大到小排序，只显示前100名）
- [ ] `fetch_github_statistics` 改名为 `fetch_github_repo_statistics` 中，表明用于获取和统计从 repo 维度的统计数据。里面的 TTF 榜单逻辑除改为存 model 外其它不变。
- [ ] 添加 `fetch_github_user_statistics` 方法，用于获取和统计针对从用户维度的统计数据（月度榜单、潜力榜单）。增加统计贡献月榜榜单信息的逻辑，里面遍历社区中所有绑定了 github 账户的用户。
- [ ] 月度榜单贡献数据获取统计逻辑：待确定
- [ ] 潜力榜单贡献数据获取统计逻辑：待确定

**Comment by chenhengjie123** [comment]
功能均已完成并上线，关闭 issue .
