### ISSUE TITLE
首页缺少分类导航

### ISSUE THREAD

**Issue by DoctorQ** [testerhome/homeland#11]
# 线下
![9c245fc2-e814-4f32-b20e-5647375e9692](https://cloud.githubusercontent.com/assets/4489853/19969270/fa04c382-a212-11e6-8c11-65aa78646e0b.png)

# 线上

![217d8c28-7ec5-424e-b682-b1d5428c5ea9](https://cloud.githubusercontent.com/assets/4489853/19969306/11b03bba-a213-11e6-84ac-5d1fd90f2865.png)

**Comment by lihuazhang** [comment]
配置问题，可以直接配置的。
