### ISSUE TITLE
回复他人帖子查看自己评论时显示最佳评论功能，点击设为最佳评判提示权限问题

### ISSUE THREAD

**Issue by Github-Benjamin** [testerhome/homeland#113]
https://testerhome.com/topics/27741
非本人帖子仅回复，显示了设置为最近评论功能按钮

![image](https://user-images.githubusercontent.com/25600051/106078947-400f7e80-614f-11eb-9f0b-775ec7b66498.png)

点击后提示权限不足
![image](https://user-images.githubusercontent.com/25600051/106078955-469df600-614f-11eb-8c89-23d9ddb0780e.png)

期望：非本人帖子屏蔽该功能

**Comment by lihuazhang** [comment]
这个已经修复了吧
