### ISSUE TITLE
社区首页点击后再返回悬浮显示未去掉

### ISSUE THREAD

**Issue by xuzhenzhen** [testerhome/homeland#114]
![图片](https://user-images.githubusercontent.com/20080350/106097083-a60cfd80-6171-11eb-8fdb-125ad99feba9.png)
具体操作步骤：先从首页点击一个帖子，然后返回，显示效果如上图，应该是悬浮显示的效果未更新

**Comment by chenhengjie123** [comment]
和 https://github.com/testerhome/homeland/issues/94 重复了
