### ISSUE TITLE
屏蔽帖子后出现的提示信息

### ISSUE THREAD

**Issue by DoctorQ** [testerhome/homeland#12]
[http://122.226.73.189/topics/6282](http://122.226.73.189/topics/6282)
![a84ce344-bc72-43ef-92e6-823ee3d082ac](https://cloud.githubusercontent.com/assets/4489853/19969433/84b3977e-a213-11e6-8d23-67e462741654.png)

**Comment by lihuazhang** [comment]
节点问题。
