### ISSUE TITLE
本人信息的github仓库不显示

### ISSUE THREAD

**Issue by DoctorQ** [testerhome/homeland#13]
# 线下
![aa608726-a021-4824-9e09-4b56c636ac30](https://cloud.githubusercontent.com/assets/4489853/19969724/96059724-a214-11e6-988c-21254c48799d.png)

正确显示如下:
# 线上

![a585091f-e6c5-49a4-83d9-4d10da0c23ab](https://cloud.githubusercontent.com/assets/4489853/19969763/bd7d5d3c-a214-11e6-87fa-3617fbf0f833.png)

**Comment by lihuazhang** [comment]
代码已经提交，数据库需要重新导入。

replies 表，缺少字段 action，/home/testerhome/use_to_data_migrate_to_pg/use_to_data_migrate_to_pg

**Comment by lihuazhang** [comment]
代码已经提交，数据库需要重新导入。

replies 表，缺少字段 action，/home/testerhome/use_to_data_migrate_to_pg/use_to_data_migrate_to_pg

**Comment by lihuazhang** [comment]
github 配置 @seveniruby
