### ISSUE TITLE
发帖按钮不应放在首页菜单中,右边栏已经有+号了

### ISSUE THREAD

**Issue by DoctorQ** [testerhome/homeland#14]
![1c36b773-1be1-4c7d-bf49-3bdc7b09a26e](https://cloud.githubusercontent.com/assets/4489853/19969987/87bdd5ea-a215-11e6-9df0-30ad96dd405b.png)

**Comment by lihuazhang** [comment]
配置问题，另外我觉得这个发帖真不错。
