### ISSUE TITLE
用户名中带"."的，@的时候出现bug

### ISSUE THREAD

**Issue by DoctorQ** [testerhome/homeland#16]
> 线上 

[https://testerhome.com/topics/6284](https://testerhome.com/topics/6284)

![wechatimg654](https://cloud.githubusercontent.com/assets/4489853/19971274/86173cdc-a219-11e6-9b85-9b23ea5b18ce.jpeg)

**Comment by lihuazhang** [comment]
![image](https://cloud.githubusercontent.com/assets/872749/20028039/19e1fbbc-a361-11e6-8d2a-d06474dd2c43.png)
