### ISSUE TITLE
增加testerhome的管理员修改标识

### ISSUE THREAD

**Issue by lihuazhang** [testerhome/homeland#19]
增加testerhome的管理员修改标识

**Comment by lihuazhang** [comment]
https://github.com/testerhome/testerhome/commits/master?after=5WuicA4kP8xp2Ymz8hFz0i%2Fk82UrNjk%3D

![image](https://cloud.githubusercontent.com/assets/872749/20039127/d47261ce-a479-11e6-88f4-61fc739d5901.png)

**Comment by chenhengjie123** [comment]
已增加，此问题关闭。
