### ISSUE TITLE
顶上样式怎么会有scrollbar？

### ISSUE THREAD

**Issue by lihuazhang** [testerhome/homeland#34]
![image](https://user-images.githubusercontent.com/872749/94996285-41cc9980-05d6-11eb-8928-6666e35799fe.png)

**Comment by lanzhiheng** [comment]
@lihuazhang  什么浏览器，我这边chrome没有这个问题。

**Comment by lihuazhang** [comment]
> @lihuazhang 什么浏览器，我这边chrome没有这个问题。

chrome，是管理页面。

**Comment by lanzhiheng** [comment]
![image](https://user-images.githubusercontent.com/8858472/95595824-328a9780-0a7f-11eb-8418-bb865b6fb04c.png)

@lihuazhang 小屏幕一行摆不下的时候才会出现滚动条吧，管理页面影响不大。

**Comment by lihuazhang** [comment]
> ![image](https://user-images.githubusercontent.com/8858472/95595824-328a9780-0a7f-11eb-8418-bb865b6fb04c.png)
> 
> @lihuazhang 小屏幕一行摆不下的时候才会出现滚动条吧，管理页面影响不大。

嗯，我改了下，把scroll去掉了。
