### ISSUE TITLE
顶栏和话题节点，“臭虫广播站”名称不一致

### ISSUE THREAD

**Issue by sanlengjingvv** [testerhome/homeland#34]
顶栏：  
<img width="540" alt="default" src="https://cloud.githubusercontent.com/assets/6478615/21916560/73289d74-d97c-11e6-9ee7-82056bae4b50.png">

话题节点：  
<img width="449" alt="default" src="https://cloud.githubusercontent.com/assets/6478615/21916519/1f769384-d97c-11e6-8f2d-030254bd07b4.png">

**Comment by chenhengjie123** [comment]
@lihuazhang 你觉得用 “Bug 广播站” 比较好还是 “臭虫广播站” 比较好？

**Comment by lihuazhang** [comment]
@chenhengjie123 改成广播站吧

**Comment by chenhengjie123** [comment]
看到现在已经改成 “Bug 曝光台” 了，这个问题关闭。
