### ISSUE TITLE
消息通知分成2个tab区分关注人消息和其他通知

### ISSUE THREAD

**Issue by seveniruby** [testerhome/homeland#37]
目前关注的人多了后, 消息会有上百条. 
一些很关键的at消息和圈子的邀请通知会被埋没. 
希望可以分成2个tab. 
一个tab是关注人消息.  一个tab是消息通知

**Comment by lihuazhang** [comment]
这个等 rubychina 改吧。

**Comment by seveniruby** [comment]
为什么关闭了？都实现了？

2017-10-13 19:20 GMT+08:00 恒温 <notifications@github.com>:
