### ISSUE TITLE
非圈子用户打开私有圈子的贴子，HTTP 500 错误

### ISSUE THREAD

**Issue by sanlengjingvv** [testerhome/homeland#39]
描述：
我不是新秀圈的，在贴子列表看到 https://testerhome.com/topics/7398 ，打开会 302 重定向到 https://testerhome.com/T4

建议：
不是圈子的用户在列表看不到圈子贴比较好？

**Comment by lihuazhang** [comment]
以后会改进的，目前在宣传新功能阶段。
