### ISSUE TITLE
个人资料设置-错别字-“登陆”

### ISSUE THREAD

**Issue by sanlengjingvv** [testerhome/homeland#41]
如图：
<img width="535" alt="6c9e8f63-9b65-428d-b9a3-0eb2cec98dc6" src="https://cloud.githubusercontent.com/assets/6478615/23337763/eb503af4-fc32-11e6-9374-0773df3cb5cb.png">

**Comment by tradetribe** [comment]
什么意思？没看明白！
我倒是觉得用户注册和基本信息里的“名字”建议改为 “昵称”比较贴切、中肯！

**Comment by sanlengjingvv** [comment]
【登陆】【登录】
