### ISSUE TITLE
圈子改进

### ISSUE THREAD

**Issue by seveniruby** [testerhome/homeland#43]
- 圈子申请弹出一个介绍和备注. 介绍里面可以贴打赏二维码. 备注里面可以允许用户写留言
- 圈子内有新帖子, 自动提醒圈子的负责人. 圈子的负责人发帖, 自动提醒圈子的所有人
- 圈子的申请通过后在消息记录里面的申请内容由"批准加入"变成"已加入"
- 允许群主设置圈子的密码. 这样群主就可以在介绍里面写上问题, 密码就是答案. 可以快速筛选不符合能力或者挑选来自特定渠道的人.
- 圈子的帖子列表可以选择  私密  帖子标题可见 完全公开. 目前后两种都有了. 第一种完全私密需要加.

**Comment by lihuazhang** [comment]
>圈子的申请通过后在消息记录里面的申请内容由"批准加入"变成"已加入"

这个做不了，就像邮件一样，已经发出去的信息，是无法修改的。除非补发一封，这个意义不大。

>允许群主设置圈子的密码. 这样群主就可以在介绍里面写上问题, 密码就是答案. 可以快速筛选不符合能力或者挑选来自特定渠道的人.

这个是什么意思？圈子对于用户最终状态就两个，一个加入，一个未加入。

**Comment by lihuazhang** [comment]
- [ ] 圈子申请弹出一个介绍和备注. 介绍里面可以贴打赏二维码. 备注里面可以允许用户写留言
- [ ] 圈子内有新帖子,
- [ ] 自动提醒圈子的负责人.
- [ ] 圈子的负责人发帖, 自动提醒圈子的所有人
- [ ] 圈子的申请通过后在消息记录里面的申请内容由"批准加入"变成"已加入"
- [ ] 允许群主设置圈子的密码. 这样群主就可以在介绍里面写上问题, 密码就是答案. 可以快速筛选不符合能力或者挑选来自特定渠道的人.
- [ ] 圈子的帖子列表可以选择 私密 帖子标题可见 完全公开. 目前后两种都有了. 第一种完全私密需要加.
