### ISSUE TITLE
首页帖子列表改进

### ISSUE THREAD

**Issue by seveniruby** [testerhome/homeland#45]
- 只要有一个别人的赞即可上首页
- 只要有评论也可以上首页
- 招聘贴随机显示在首页最新帖的最后2个位置.  一个月内的招聘贴随机显示2个
- 提问帖如果有赞也可以上首页

**Comment by lihuazhang** [comment]
只要有一个别人的赞即可上首页
只要有评论也可以上首页

这两个好了。

招聘贴随机显示在首页最新帖的最后2个位置. 一个月内的招聘贴随机显示2个。这个另外看。

提问帖不用特别了。和普通帖子保持一致吧。

**Comment by seveniruby** [comment]
不错. 赞

在 2017年4月28日 下午11:55，恒温 <notifications@github.com>写道：
