### ISSUE TITLE
搜索 wda 关键字时，搜索结果页显示内容和实际帖子内容不一致

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/homeland#54]
步骤：在首页右上角搜索关键字 wda ，回车进行搜索。

预期结果：
搜索结果中，所有搜索结果页的标题、摘要信息均与实际链接到的帖子信息一致

实际结果：
![image](https://cloud.githubusercontent.com/assets/2800797/25936252/704585d8-3659-11e7-8cab-24f15297f397.png)

另外测试了一下关键字 “关于 appium1.6.4-beta ios 真机 wda 断开连接” ，发现搜索结果页仍存在显示内容和实际链接地址内容不一致的情况。

**Comment by lihuazhang** [comment]
嗯 这个问题是index没有更新，不知道为啥。 以后要做个crontab了。
