### ISSUE TITLE
添加开源测试项目模块

### ISSUE THREAD

**Issue by lihuazhang** [testerhome/homeland#61]
添加开源测试项目模块：

- [x] 用户增删改查开源项目
- [x] admin增删改查开源项目
- [x] 点评开源项目
- [x] 点赞
- [ ] 踩

**Comment by seveniruby** [comment]
踩的需求我已经评论了。可以做出管理员可见。目前开源项目这个实现的不错了。后期的界面希望还是可以大气点，支持多种布局。
