### ISSUE TITLE
对帖子添加“踩”

### ISSUE THREAD

**Issue by lihuazhang** [testerhome/homeland#63]
关键字:赞成、反对

**Comment by seveniruby** [comment]
这个还是不要做了，做了就没人发帖了吧。我觉得加了踩，仅供管理员可见吧。不要对发帖人可见。不然随便有一个贴就会导致发帖人分享积极性大减。

**Comment by chenhengjie123** [comment]
这个已经有个下沉帖子的功能了，功能接近。这个 Issue 先关掉。
