### ISSUE TITLE
管理员屏蔽贴的信息提示显示出错

### ISSUE THREAD

**Issue by DoctorQ** [testerhome/homeland#7]
# 测试环境
[http://122.226.73.189/topics/6270](http://122.226.73.189/topics/6270)

显示如下：

![07f03ba6-6851-4bcf-81f6-96086fde563e](https://cloud.githubusercontent.com/assets/4489853/19934646/5a51f5a0-a152-11e6-8605-fe200f7c1fd8.png)

正确显示应该如下:

# 线上环境

[https://testerhome.com/topics/6270](https://testerhome.com/topics/6270)

![b1ca70f2-1194-442e-b44a-896cc5c6e75d](https://cloud.githubusercontent.com/assets/4489853/19934697/90a190fc-a152-11e6-9d40-b289401bc0ec.png)

**Comment by lihuazhang** [comment]
代码已经提交，数据库需要重新导入。

replies 表，缺少字段 action，/home/testerhome/use_to_data_migrate_to_pg/use_to_data_migrate_to_pg
