### ISSUE TITLE
【新需求】举报功能

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/homeland#90]
# 背景

目前随着社区发展，内容逐渐增多，管理员无法一一审核管理。需要提供一个方便的入口，便于社区的所有同学对于觉得有问题的内容进行举报，协助管理。

# 功能叙述

1. 在文章/帖子/开源项目，有一个举报按钮，一键举报
![image](https://user-images.githubusercontent.com/2800797/49692534-03abed80-fb98-11e8-8046-4b37b51d7724.png)
![image](https://user-images.githubusercontent.com/2800797/49692541-0dcdec00-fb98-11e8-85cd-5763eb04a4b9.png)
2. 举报后，消息仅管理员及举报人可见，管理员会收到论坛消息提醒，亦可在管理后台查看到消息
3. 举报时需给出联系邮箱（默认使用论坛注册时留下的邮箱），便于管理员回复
4. 管理员开始后，点击【已跟进】按钮，此时也会发出仅管理员可见的消息提醒

# 功能点（按优先级排序）

- [ ] 1.  开源项目可一键举报
- [ ] 2.  管理员在后台可以看到举报消息（举报人id、举报人联系邮箱、举报信息类型、举报信息内容、被举报项目名称、被举报项目地址）
- [ ] 3.  管理员可点击【已跟进】表示跟进中
- [ ] 4.  管理员可收到【有新举报】和【举报已由xxx跟进】消息提醒
- [ ] 5.  其它类型（帖子/文章、回复、wiki等）也支持举报

# 技术设计

待补充

**Comment by lihuazhang** [comment]
举报理由用 enum 类型吧？可以把enum类定义下。__

**Comment by lihuazhang** [comment]
另外，某个人如果被举报操作10次，就要发起管理员会审，是否要ban了这个用户。 @chenhengjie123

**Comment by ariesliu** [comment]
开源项目为什么要加举报功能？是抄袭还是非法开源？

**Comment by chenhengjie123** [comment]
> 开源项目为什么要加举报功能？是抄袭还是非法开源？我以为这个举报功能只针对topic或者column内容呢

这个举报功能我计划是设计成所有东西（如文章、回复、开源项目等）都可以举报。

**Comment by chenhengjie123** [comment]
> 另外，某个人如果被举报操作10次，就要发起管理员会审，是否要ban了这个用户。 @chenhengjie123

这个统计功能二期加入吧，一期我想先简单点，有个可以收到举报并回复的功能。

**Comment by chenhengjie123** [comment]
# 技术设计：

* model 层
名称：tipOff
字段：
reporterId:integer 举报人用户id
reporterEmail:string 举报人邮箱地址，用于回复
description:string 举报说明
createTime:datetime 举报时间
type:string 举报类型（垃圾广告、违规内容、不友善内容、其它理由）
url:string 被举报内容 url 
dealer:integer 处理的管理员用户id
dealTime:datetime 处理时间

* controller 层
增加一个 tipOffController ，具备几个功能：
1. 普通用户用：举报创建、查询（查看本人已发举报）
2. 管理员界面用：查询（按状态查看所有举报信息）、设定跟进中（添加处理人）
3. 创建、设定跟进中加上消息通知，类型为 system ，接收人为全体管理员。
4. 设定跟进中加上消息通知，类型为 system ，接收人为举报人。

* view层
1. topic及专栏文章 _show.html.erb 页增加举报按钮
2. topic 增加 _tipOff.html.erb 弹窗页面
3. user menu 增加举报历史页（仅本用户可见，不公开）
4. admin 增加举报列表页，查看所有举报及一键设定跟进

**Comment by chenhengjie123** [comment]
* model 层
微调后方案及完成情况

- [ ] 名称：tipOff

字段：
reporterId:integer 举报人用户id
reporterEmail:string 举报人邮箱地址，用于回复
description:string 举报说明
createTime:datetime 举报时间
type:string 举报类型（垃圾广告、违规内容、不友善内容、其它理由）
url:string 被举报内容 url
followerId:integer 跟进的管理员用户id
followTime:datetime 跟进时间
```
      t.integer :reporter_id
      t.string :reporter_email
      t.string :tip_off_type
      t.string :body
      t.datetime :create_time
      t.string :content_url
      t.integer :follower_id
      t.datetime :follow_time
      t.datetime :deleted_at
```

* controller 层
增加一个 tipOffController ，具备几个功能：

- [ ] 普通用户用：举报创建、查询（查看本人已发举报）
- [ ] 管理员界面用：查询（按状态查看所有举报信息）、设定跟进中（添加处理人）
- [ ] 创建、设定跟进中加上消息通知，类型为 system ，接收人为全体管理员。
- [ ] 设定跟进中加上消息通知，类型为 system ，接收人为举报人。

* view层

- [ ] topic及专栏文章 _show.html.erb 页增加举报按钮
- [ ] topic 增加 _tipOff.html.erb 弹窗页面
- [ ] user menu 增加举报历史页（仅本用户可见，不公开）
- [ ] admin 增加举报列表页，可按时间倒序查看所有举报及一键设定跟进（点击人会被记录为跟进人）。

**Comment by chenhengjie123** [comment]
考虑到跟进结果也是大家比较关心的，因此增加了跟进结果字段，对应地，改为只有跟进完成后，再直接在后台登记跟进结果，提示用户已完成跟进。去掉跟进中这个中间状态。

自测用例：
![image](https://user-images.githubusercontent.com/2800797/52458280-7ab23200-2b99-11e9-959e-b412a4b5fd8a.png)

**Comment by chenhengjie123** [comment]
功能已开发完毕并上线，目前使用正常，此 issue 先关闭。
