### ISSUE TITLE
修改圈子的图标展示

### ISSUE THREAD

**Issue by seveniruby** [testerhome/homeland#98]
现在的图标在个人资料中，只展示了图标，希望修改为一行一个，展示图标和名字

这是现在的样式
![image](https://user-images.githubusercontent.com/1222769/63310969-3c0ee880-c32f-11e9-8203-0effd8dbab37.png)

期望修改为
![image](https://user-images.githubusercontent.com/1222769/63311074-9740db00-c32f-11e9-8d2c-eadd5c2abdcf.png)

**Comment by chenhengjie123** [comment]
已上线，此 issue 关闭。

**Comment by seveniruby** [comment]
实现的效果不错，很给力。
